"""make counter

Revision ID: 9e5f21b93fd0
Revises: 404e872cae36
Create Date: 2020-06-23 02:00:22.741420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5f21b93fd0'
down_revision = '404e872cae36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_url', sa.Column('counter', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_url', 'counter')
    # ### end Alembic commands ###
